##==============================================================
## Config

$(BUILDDIR)/etc:
	mkdir --parents $@

CONFIG_SOURCES = $(shell find $(SRCDIR)/config -name '*.in')
CONFIG_FILES = $(CONFIG_SOURCES:$(SRCDIR)/config/%.in=$(BUILDDIR)/etc/%)

$(CONFIG_FILES): $(BUILDDIR)/etc/%: $(SRCDIR)/config/%.in | $(BUILDDIR)/etc
	$(call substitute,$<,$@)
	chmod +x $@

_config: $(CONFIG_FILES)

clean_config:
	rm -rf $(CONFIG_FILES)

.PHONY += _config clean_config