include ../config.mk

all: build

build: scripts boot_scripts config

clean: clean_scripts clean_boot_scripts clean_config


##==============================================================
## Scripts

SCRIPT_SOURCES = $(shell find scripts -name '*.in')
SCRIPTS = $(SCRIPT_SOURCES:scripts/%.in=bin/%)

$(SCRIPTS): bin/%: scripts/%.in
	$(call substitute,$<,$@)
	chmod +x $@

scripts: $(SCRIPTS) ebin/user_default.beam

clean_scripts:
	rm $(SCRIPTS)

ebin:
	mkdir $@

ebin/user_default.beam: user_default.erl | ebin
	erlc -pa ebin/ -o ebin/ -DDev -DTEST -DEUNIT $<

##==============================================================
## Boot Scripts

boot:
	mkdir --parents $@

boot_scripts: bin/make-boot-script | boot
	cd boot && \
	ERL_LIBS="$(SRCDIR)/src" ../bin/make-boot-script

clean_boot_scripts:
	rm -rf boot

##==============================================================
## Config

etc:
	mkdir --parents $@

CONFIG_SOURCES = $(shell find config -name '*.in')
CONFIG_FILES = $(CONFIG_SOURCES:config/%.in=etc/%)

$(CONFIG_FILES): etc/%: config/%.in | etc
	$(call substitute,$<,$@)
	chmod +x $@

config: $(CONFIG_FILES)

clean_config:
	rm -rf $(CONFIG_FILES)